// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/search-customers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect this app with your account first." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function rows(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
    structuredContent: { data: data ?? [] }
  };
}

// src/lib/mcp/tools/search-customers.ts
var search_customers_default = defineTool({
  name: "search_customers",
  title: "Search customers",
  description: "Search the travel agency's customers by name, email, or phone.",
  inputSchema: {
    query: z.string().trim().describe("Name, email, or phone fragment to search for."),
    limit: z.number().int().describe("Maximum number of customers to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const like = `%${query.replace(/[%,]/g, "")}%`;
    const { data, error } = await supabase.from("customers").select("id, name, email, phone, nationality, total_bookings, total_spent, last_booking_date").or(`name.ilike.${like},email.ilike.${like},phone.ilike.${like}`).order("last_booking_date", { ascending: false, nullsFirst: false }).limit(take);
    if (error) return failure(error.message);
    return rows(data);
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4";
var list_bookings_default = defineTool2({
  name: "list_bookings",
  title: "List bookings",
  description: "List bookings for the signed-in user's organization, optionally filtered by status or travel start date range.",
  inputSchema: {
    status: z2.string().trim().describe("Booking status filter, e.g. pending, confirmed, cancelled.").optional(),
    start_from: z2.string().trim().describe("Only bookings starting on or after this ISO date (YYYY-MM-DD).").optional(),
    start_to: z2.string().trim().describe("Only bookings starting on or before this ISO date (YYYY-MM-DD).").optional(),
    limit: z2.number().int().describe("Maximum number of bookings to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, start_from, start_to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select(
      "id, booking_number, booking_type, status, workflow_stage, customer_name, supplier_name, start_date, end_date, selling_price, currency, created_at"
    ).order("start_date", { ascending: true, nullsFirst: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (start_from) query = query.gte("start_date", start_from);
    if (start_to) query = query.lte("start_date", start_to);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return rows(data);
  }
});

// src/lib/mcp/tools/get-booking.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4";
var get_booking_default = defineTool3({
  name: "get_booking",
  title: "Get booking",
  description: "Fetch one booking by its booking number (e.g. BK-123456) or its id.",
  inputSchema: {
    booking_number: z3.string().trim().describe("Booking number such as BK-1783866510972.").optional(),
    id: z3.string().trim().describe("Booking UUID.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_number, id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    if (!booking_number && !id) return failure("Provide either booking_number or id.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select(
      "id, booking_number, booking_type, status, workflow_stage, customer_id, customer_name, supplier_name, start_date, end_date, selling_price, cost_price, profit, currency, payment_policy, deposit_percent, notes, created_at, updated_at"
    ).limit(1);
    query = id ? query.eq("id", id) : query.eq("booking_number", booking_number);
    const { data, error } = await query.maybeSingle();
    if (error) return failure(error.message);
    if (!data) return failure("Booking not found or not visible to this account.");
    return rows(data);
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^4";
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "List sales leads",
  description: "List sales pipeline leads (SOP leads) for the signed-in user's organization, newest arrivals first.",
  inputSchema: {
    stage: z4.string().trim().describe("Pipeline stage filter, e.g. new, assigned, qualified, pricing_requested, quoted, lost.").optional(),
    destination: z4.string().trim().describe("Filter by destination fragment.").optional(),
    limit: z4.number().int().describe("Maximum number of leads to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, destination, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("sop_leads").select(
      "id, lead_number, stage, contact_name, contact_phone, contact_email, destination, city, check_in, check_out, adults, children_count, budget_amount, budget_currency, lead_source, current_owner_id, arrived_at"
    ).order("arrived_at", { ascending: false }).limit(take);
    if (stage) query = query.eq("stage", stage);
    if (destination) query = query.ilike("destination", `%${destination.replace(/[%,]/g, "")}%`);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return rows(data);
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^4";
var list_quotes_default = defineTool5({
  name: "list_quotes",
  title: "List quotes",
  description: "List customer quotations for the signed-in user's organization, newest first.",
  inputSchema: {
    status: z5.string().trim().describe("Quote status filter, e.g. draft, sent, accepted, rejected.").optional(),
    customer_name: z5.string().trim().describe("Filter by customer name fragment.").optional(),
    limit: z5.number().int().describe("Maximum number of quotes to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, customer_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("quotes").select(
      "id, quote_number, status, customer_name, destination, travel_date, return_date, number_of_travelers, total_amount, valid_until, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (customer_name) query = query.ilike("customer_name", `%${customer_name.replace(/[%,]/g, "")}%`);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return rows(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "gvozalurfthzxpuasplo";
var mcp_default = defineMcp({
  name: "vogatchi-voyage-connect",
  title: "vogatchi-voyage-connect",
  version: "0.1.0",
  instructions: "Read-only tools for the Vogatchi travel concierge platform. Use search_customers to find a client, list_leads for the sales pipeline, list_quotes for quotations, and list_bookings / get_booking for reservations. All data is scoped to the signed-in user's organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_customers_default, list_leads_default, list_quotes_default, list_bookings_default, get_booking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
