-- Launch hardening: canonical financial formulas, single-source journal posting,
-- payment allocation integrity, and a reversible audit trail.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Preserve every production row changed by this migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.financial_repair_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_key text NOT NULL,
  organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  reason text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.financial_repair_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.financial_repair_audit FROM PUBLIC, anon;
GRANT SELECT ON public.financial_repair_audit TO authenticated;
GRANT ALL ON public.financial_repair_audit TO service_role;

DROP POLICY IF EXISTS financial_repair_audit_read ON public.financial_repair_audit;
CREATE POLICY financial_repair_audit_read
  ON public.financial_repair_audit FOR SELECT TO authenticated
  USING (organization_id IS NOT NULL AND public.user_belongs_to_org(auth.uid(), organization_id));

-- ---------------------------------------------------------------------------
-- 2) Remove overlapping legacy posting triggers before touching live data.
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_booking_to_journal_ins ON public.bookings;
DROP TRIGGER IF EXISTS trg_booking_to_journal_upd ON public.bookings;
DROP TRIGGER IF EXISTS trg_invoice_journal ON public.invoices;
DROP TRIGGER IF EXISTS trg_invoice_payment_journal ON public.invoices;
DROP TRIGGER IF EXISTS trg_expense_journal ON public.expense_transactions;
DROP TRIGGER IF EXISTS trg_supplier_payment_journal ON public.supplier_payments;
DROP TRIGGER IF EXISTS trg_supplier_payment_bank ON public.supplier_payments;
DROP TRIGGER IF EXISTS trg_post_invoice ON public.invoices;
DROP TRIGGER IF EXISTS trg_post_invoice_legacy_receipt ON public.invoices;
DROP TRIGGER IF EXISTS trg_post_booking_cost ON public.bookings;
DROP TRIGGER IF EXISTS trg_post_supplier_payment ON public.supplier_payments;
DROP TRIGGER IF EXISTS trg_post_expense ON public.expense_transactions;
DROP TRIGGER IF EXISTS trg_customer_payment_to_journal ON public.customer_payments;

-- New supplier payments must retain the treasury account used to pay them.
ALTER TABLE public.supplier_payments
  ADD COLUMN IF NOT EXISTS treasury_account_id uuid
    REFERENCES public.bank_accounts(id) ON DELETE SET NULL;

-- Accounts required for overpayments/customer advances, refunds, and current earnings.
INSERT INTO public.chart_of_accounts (
  organization_id, account_code, account_name, account_name_ar,
  account_type, is_active, is_system, description
)
SELECT o.id, v.code, v.name_en, v.name_ar, v.kind::public.account_type,
       true, true, v.description
FROM public.organizations o
CROSS JOIN (VALUES
  ('2050', 'Customer Advances', 'دفعات مقدمة من العملاء', 'liability', 'Unallocated customer receipts and overpayments'),
  ('3999', 'Current Earnings', 'أرباح الفترة الحالية', 'equity', 'Synthetic management-report current earnings'),
  ('4050', 'Sales Returns & Allowances', 'مردودات ومسموحات المبيعات', 'revenue', 'Contra-revenue used for paid customer refunds')
) AS v(code, name_en, name_ar, kind, description)
ON CONFLICT (organization_id, account_code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3) Canonical formulas at the database boundary.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.normalize_booking_financials()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.selling_price := COALESCE(NEW.selling_price, 0);
  NEW.cost_price := COALESCE(NEW.cost_price, 0);
  NEW.profit := NEW.selling_price - NEW.cost_price;

  IF COALESCE(NEW.status, 'pending') IN ('confirmed', 'completed')
     AND (
       NEW.selling_price <= 0 OR NEW.cost_price <= 0
       OR NEW.start_date IS NULL OR NEW.end_date IS NULL
       OR NEW.start_date > NEW.end_date
       OR (NEW.cost_price > 0 AND NEW.supplier_id IS NULL)
     ) THEN
    NEW.data_quality_status := 'incomplete';
  ELSIF NEW.start_date IS NOT NULL AND NEW.end_date IS NOT NULL
        AND NEW.start_date > NEW.end_date THEN
    NEW.data_quality_status := 'review_needed';
  ELSE
    NEW.data_quality_status := 'ok';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_normalize_booking_financials ON public.bookings;
CREATE TRIGGER trg_normalize_booking_financials
BEFORE INSERT OR UPDATE OF selling_price, cost_price, status, start_date, end_date, supplier_id
ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.normalize_booking_financials();

CREATE OR REPLACE FUNCTION public.normalize_invoice_totals()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_net numeric;
BEGIN
  NEW.subtotal := COALESCE(NEW.subtotal, 0);
  NEW.discount_amount := COALESCE(NEW.discount_amount, 0);
  NEW.vat_rate := COALESCE(NEW.vat_rate, 0);
  NEW.total_paid_amount := COALESCE(NEW.total_paid_amount, 0);

  IF NEW.subtotal < 0 OR NEW.discount_amount < 0 OR NEW.vat_rate < 0
     OR NEW.total_paid_amount < 0 THEN
    RAISE EXCEPTION 'Invoice amounts and VAT rate must be non-negative';
  END IF;
  IF NEW.discount_amount > NEW.subtotal THEN
    RAISE EXCEPTION 'Invoice discount cannot exceed subtotal';
  END IF;

  v_net := NEW.subtotal - NEW.discount_amount;
  NEW.vat_amount := round(v_net * NEW.vat_rate / 100, 2);
  NEW.final_amount := round(v_net + NEW.vat_amount, 2);

  IF NEW.total_paid_amount > NEW.final_amount THEN
    RAISE EXCEPTION 'Invoice paid amount cannot exceed final amount';
  END IF;

  NEW.remaining_amount := round(NEW.final_amount - NEW.total_paid_amount, 2);
  NEW.payment_status := CASE
    WHEN NEW.final_amount > 0 AND NEW.total_paid_amount >= NEW.final_amount THEN 'paid'
    WHEN NEW.total_paid_amount > 0 THEN 'partial'
    ELSE 'unpaid'
  END;

  IF NEW.payment_status = 'paid' AND COALESCE(NEW.status, 'draft') <> 'cancelled' THEN
    NEW.status := 'paid';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_normalize_invoice_totals ON public.invoices;
CREATE TRIGGER trg_normalize_invoice_totals
BEFORE INSERT OR UPDATE OF subtotal, discount_amount, vat_rate, vat_amount,
  final_amount, total_paid_amount
ON public.invoices
FOR EACH ROW EXECUTE FUNCTION public.normalize_invoice_totals();

-- ---------------------------------------------------------------------------
-- 4) Deterministic repair of known formula/date/allocation defects.
-- ---------------------------------------------------------------------------
INSERT INTO public.financial_repair_audit (
  migration_key, organization_id, entity_type, entity_id, before_data, reason
)
SELECT '20260822_financial_launch', b.organization_id, 'booking', b.id, to_jsonb(b),
       'Correct booking profit to selling_price - cost_price'
FROM public.bookings b
WHERE abs(COALESCE(b.profit,0) - (COALESCE(b.selling_price,0) - COALESCE(b.cost_price,0))) > 0.01;

INSERT INTO public.financial_repair_audit (
  migration_key, organization_id, entity_type, entity_id, before_data, reason
)
SELECT '20260822_financial_launch', b.organization_id, 'booking', b.id, to_jsonb(b),
       'Correct clearly truncated imported year 0205 to 2025'
FROM public.bookings b
WHERE b.booking_number = 'VGT-IMP-2025-0176' AND b.start_date = DATE '0205-10-10';

INSERT INTO public.financial_repair_audit (
  migration_key, organization_id, entity_type, entity_id, before_data, reason
)
SELECT '20260822_financial_launch', i.organization_id, 'invoice', i.id, to_jsonb(i),
       'Recompute canonical invoice totals and remaining balance'
FROM public.invoices i
WHERE abs(COALESCE(i.final_amount,0) - (
        COALESCE(i.subtotal,0) - COALESCE(i.discount_amount,0) + COALESCE(i.vat_amount,0)
      )) > 0.01
   OR abs(COALESCE(i.remaining_amount,0) - GREATEST(
        COALESCE(i.final_amount,0) - COALESCE(i.total_paid_amount,0), 0
      )) > 0.01;

UPDATE public.bookings
SET start_date = DATE '2025-10-10'
WHERE booking_number = 'VGT-IMP-2025-0176' AND start_date = DATE '0205-10-10';

UPDATE public.invoices i
SET issued_date = DATE '2025-10-10'
FROM public.bookings b
WHERE i.booking_id=b.id
  AND b.booking_number='VGT-IMP-2025-0176'
  AND i.issued_date=DATE '0205-10-10';

UPDATE public.bookings b
SET profit = COALESCE(b.selling_price,0) - COALESCE(b.cost_price,0),
    data_quality_status = CASE
      WHEN COALESCE(b.status,'pending') IN ('confirmed','completed')
       AND (
         COALESCE(b.selling_price,0) <= 0 OR COALESCE(b.cost_price,0) <= 0
         OR b.start_date IS NULL OR b.end_date IS NULL OR b.start_date > b.end_date
         OR (COALESCE(b.cost_price,0) > 0 AND b.supplier_id IS NULL)
       ) THEN 'incomplete'
      WHEN b.start_date IS NOT NULL AND b.end_date IS NOT NULL AND b.start_date > b.end_date
        THEN 'review_needed'
      ELSE 'ok'
    END
WHERE abs(COALESCE(b.profit,0) - (COALESCE(b.selling_price,0)-COALESCE(b.cost_price,0))) > 0.01
   OR b.data_quality_status IS DISTINCT FROM CASE
      WHEN COALESCE(b.status,'pending') IN ('confirmed','completed')
       AND (
         COALESCE(b.selling_price,0) <= 0 OR COALESCE(b.cost_price,0) <= 0
         OR b.start_date IS NULL OR b.end_date IS NULL OR b.start_date > b.end_date
         OR (COALESCE(b.cost_price,0) > 0 AND b.supplier_id IS NULL)
       ) THEN 'incomplete'
      WHEN b.start_date IS NOT NULL AND b.end_date IS NOT NULL AND b.start_date > b.end_date
        THEN 'review_needed'
      ELSE 'ok'
    END;

-- Existing customer receipts were created before allocation support was wired.
-- Allocate only the outstanding invoice amount; any excess remains a customer advance.
INSERT INTO public.customer_payment_allocations (
  organization_id, payment_id, invoice_id, amount, amount_base
)
SELECT p.organization_id, p.id, p.invoice_id,
       LEAST(p.amount, GREATEST(COALESCE(i.final_amount,0)-COALESCE(i.total_paid_amount,0),0)),
       round(
         LEAST(p.amount, GREATEST(COALESCE(i.final_amount,0)-COALESCE(i.total_paid_amount,0),0))
         * COALESCE(p.exchange_rate,1), 2
       )
FROM public.customer_payments p
JOIN public.invoices i ON i.id=p.invoice_id AND i.organization_id=p.organization_id
WHERE p.status='completed'
  AND p.currency=COALESCE(i.currency,'EGP')
  AND GREATEST(COALESCE(i.final_amount,0)-COALESCE(i.total_paid_amount,0),0) > 0
  AND NOT EXISTS (
    SELECT 1 FROM public.customer_payment_allocations a WHERE a.payment_id=p.id
  );

UPDATE public.invoices i
SET total_paid_amount = LEAST(i.final_amount, x.allocated),
    remaining_amount = GREATEST(i.final_amount - x.allocated, 0),
    payment_status = CASE
      WHEN x.allocated >= i.final_amount AND i.final_amount > 0 THEN 'paid'
      WHEN x.allocated > 0 THEN 'partial'
      ELSE 'unpaid'
    END,
    status = CASE
      WHEN x.allocated >= i.final_amount AND i.final_amount > 0 THEN 'paid'
      ELSE i.status
    END
FROM (
  SELECT invoice_id, SUM(amount) AS allocated
  FROM public.customer_payment_allocations
  GROUP BY invoice_id
) x
WHERE i.id=x.invoice_id;

-- Invoke the invoice normalizer for all rows, repairing the two stale remaining balances.
UPDATE public.invoices SET subtotal=subtotal;

-- Repair old reporting-only account codes.
UPDATE public.finance_transactions
SET account_code='1100', memo=replace(COALESCE(memo,''), 'AR reduction', 'Accounts receivable reduction')
WHERE reference_type='customer_payment' AND account_code='1200';

UPDATE public.finance_transactions
SET account_code='2000', memo=replace(COALESCE(memo,''), 'AP reduction', 'Accounts payable reduction')
WHERE reference_type='supplier_payment' AND account_code='2100';

UPDATE public.finance_transactions
SET account_code='4050', memo='Customer refund / sales return'
WHERE reference_type='refund' AND account_code='1200';

-- New/changed rows are rejected when financially invalid. Constraints are
-- installed after the deterministic repair so unresolved imports can be
-- flagged without guessing a replacement value. NOT VALID keeps those legacy
-- exceptions visible while enforcing the rule on every future write.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='bookings_financial_nonnegative') THEN
    ALTER TABLE public.bookings ADD CONSTRAINT bookings_financial_nonnegative
      CHECK (COALESCE(selling_price,0) >= 0 AND COALESCE(cost_price,0) >= 0) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='bookings_valid_date_range') THEN
    ALTER TABLE public.bookings ADD CONSTRAINT bookings_valid_date_range
      CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='bookings_valid_deposit_percent') THEN
    ALTER TABLE public.bookings ADD CONSTRAINT bookings_valid_deposit_percent
      CHECK (deposit_percent IS NULL OR deposit_percent BETWEEN 0 AND 100) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='invoices_financial_nonnegative') THEN
    ALTER TABLE public.invoices ADD CONSTRAINT invoices_financial_nonnegative
      CHECK (
        COALESCE(subtotal,0) >= 0 AND COALESCE(vat_rate,0) >= 0
        AND COALESCE(vat_amount,0) >= 0 AND COALESCE(discount_amount,0) >= 0
        AND COALESCE(final_amount,0) >= 0 AND COALESCE(total_paid_amount,0) >= 0
        AND COALESCE(remaining_amount,0) >= 0
        AND COALESCE(discount_amount,0) <= COALESCE(subtotal,0)
        AND COALESCE(total_paid_amount,0) <= COALESCE(final_amount,0)
      ) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='customer_payments_exchange_rate_positive') THEN
    ALTER TABLE public.customer_payments ADD CONSTRAINT customer_payments_exchange_rate_positive
      CHECK (exchange_rate > 0) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='supplier_payments_amount_positive') THEN
    ALTER TABLE public.supplier_payments ADD CONSTRAINT supplier_payments_amount_positive
      CHECK (amount > 0 AND COALESCE(exchange_rate,1) > 0) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='customer_payments_treasury_required') THEN
    ALTER TABLE public.customer_payments ADD CONSTRAINT customer_payments_treasury_required
      CHECK (payment_method='cash' OR treasury_account_id IS NOT NULL) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='supplier_payments_treasury_required') THEN
    ALTER TABLE public.supplier_payments ADD CONSTRAINT supplier_payments_treasury_required
      CHECK (payment_method='cash' OR treasury_account_id IS NOT NULL) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='expenses_treasury_required') THEN
    ALTER TABLE public.expense_transactions ADD CONSTRAINT expenses_treasury_required
      CHECK (payment_method='cash' OR bank_account_id IS NOT NULL) NOT VALID;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 5) Source-tracked posting engine (exactly one entry per business event).
-- ---------------------------------------------------------------------------
-- The legacy implementation cast the whole date+sequence string to int4 and
-- already overflows in production (for example 20260720260). Serialize number
-- allocation per organization and only parse the trailing sequence as bigint.
CREATE OR REPLACE FUNCTION public._next_entry_number(_org uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_next bigint;
  v_prefix text := 'JE-'||to_char(CURRENT_DATE,'YYYYMM')||'-';
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(_org::text,0));
  SELECT COALESCE(MAX(x.seq),0)+1 INTO v_next
  FROM (
    SELECT substring(entry_number FROM '([0-9]+)$')::bigint AS seq
    FROM public.journal_entries
    WHERE organization_id=_org AND entry_number LIKE v_prefix||'%'
  ) x;
  RETURN v_prefix||lpad(v_next::text,5,'0');
END;
$$;

CREATE OR REPLACE FUNCTION public.post_booking_cost(_booking_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  b public.bookings%ROWTYPE;
  v_je uuid;
  v_cogs uuid;
  v_ap uuid;
  v_cost_code text;
BEGIN
  SELECT * INTO b FROM public.bookings WHERE id=_booking_id;
  IF NOT FOUND THEN RETURN NULL; END IF;

  SELECT id INTO v_je FROM public.journal_entries
  WHERE organization_id=b.organization_id AND source_type='booking_cost' AND source_id=b.id;

  IF b.is_demo OR COALESCE(b.status,'pending') NOT IN ('confirmed','completed')
     OR COALESCE(b.cost_price,0) <= 0 THEN
    IF v_je IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
    ) THEN
      DELETE FROM public.journal_entries WHERE id=v_je;
    END IF;
    RETURN NULL;
  END IF;

  IF v_je IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
  ) THEN
    RETURN v_je;
  END IF;

  v_cost_code := CASE b.booking_type
    WHEN 'flight' THEN '5010'
    WHEN 'transport' THEN '5020'
    WHEN 'car_rental' THEN '5030'
    ELSE '5000'
  END;
  v_cogs := COALESCE(public._resolve_account(b.organization_id,v_cost_code),
                     public._resolve_account(b.organization_id,'5000'));
  v_ap := public._resolve_account(b.organization_id,'2000');
  IF v_cogs IS NULL OR v_ap IS NULL THEN
    RAISE EXCEPTION 'Missing COGS/AP account for organization %', b.organization_id;
  END IF;

  DELETE FROM public.journal_entries WHERE id=v_je AND NOT is_locked;
  INSERT INTO public.journal_entries (
    organization_id,entry_number,entry_date,reference_type,reference_id,description,
    total_debit,total_credit,status,currency,source_type,source_id,booking_id,
    functional_currency,fx_rate,posted_at,auto_generated
  ) VALUES (
    b.organization_id,public._next_entry_number(b.organization_id),
    COALESCE(b.start_date,b.created_at::date,CURRENT_DATE),'booking_cost',b.id,
    'تكلفة حجز '||b.booking_number,b.cost_price,b.cost_price,'posted',
    COALESCE(b.currency,'EGP'),'booking_cost',b.id,b.id,COALESCE(b.currency,'EGP'),1,now(),true
  ) RETURNING id INTO v_je;

  INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
  VALUES
    (v_je,v_cogs,b.cost_price,0,'تكلفة حجز '||b.booking_number,1),
    (v_je,v_ap,0,b.cost_price,'ذمم المورد - '||COALESCE(b.supplier_name,''),2);
  RETURN v_je;
END;
$$;

CREATE OR REPLACE FUNCTION public.post_invoice(_invoice_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  i public.invoices%ROWTYPE;
  v_je uuid;
  v_ar uuid;
  v_revenue uuid;
  v_tax uuid;
  v_revenue_code text;
  v_net numeric;
BEGIN
  SELECT * INTO i FROM public.invoices WHERE id=_invoice_id;
  IF NOT FOUND OR i.organization_id IS NULL THEN RETURN NULL; END IF;

  SELECT id INTO v_je FROM public.journal_entries
  WHERE organization_id=i.organization_id AND source_type='invoice' AND source_id=i.id;

  IF i.is_demo OR COALESCE(i.status,'draft') IN ('draft','cancelled')
     OR COALESCE(i.final_amount,0) <= 0 THEN
    IF v_je IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
    ) THEN
      DELETE FROM public.journal_entries WHERE id=v_je;
    END IF;
    RETURN NULL;
  END IF;

  IF v_je IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
  ) THEN
    RETURN v_je;
  END IF;

  v_revenue_code := CASE i.booking_type
    WHEN 'hotel' THEN '4000'
    WHEN 'flight' THEN '4010'
    WHEN 'transport' THEN '4020'
    WHEN 'car_rental' THEN '4030'
    ELSE '4040'
  END;
  v_ar := public._resolve_account(i.organization_id,'1100');
  v_revenue := COALESCE(public._resolve_account(i.organization_id,v_revenue_code),
                        public._resolve_account(i.organization_id,'4000'));
  v_tax := public._resolve_account(i.organization_id,'2100');
  v_net := round(COALESCE(i.subtotal,0)-COALESCE(i.discount_amount,0),2);

  IF v_ar IS NULL OR v_revenue IS NULL OR (COALESCE(i.vat_amount,0)>0 AND v_tax IS NULL) THEN
    RAISE EXCEPTION 'Missing AR/revenue/tax account for organization %', i.organization_id;
  END IF;
  IF abs(v_net + COALESCE(i.vat_amount,0) - i.final_amount) > 0.01 THEN
    RAISE EXCEPTION 'Invoice % is not balanced after discount and VAT', i.invoice_number;
  END IF;

  DELETE FROM public.journal_entries WHERE id=v_je AND NOT is_locked;
  INSERT INTO public.journal_entries (
    organization_id,entry_number,entry_date,reference_type,reference_id,description,
    total_debit,total_credit,status,currency,source_type,source_id,booking_id,
    functional_currency,fx_rate,posted_at,auto_generated
  ) VALUES (
    i.organization_id,public._next_entry_number(i.organization_id),
    COALESCE(i.issued_date,i.created_at::date,CURRENT_DATE),'invoice',i.id,
    'فاتورة '||i.invoice_number,i.final_amount,i.final_amount,'posted',
    COALESCE(i.currency,'EGP'),'invoice',i.id,i.booking_id,COALESCE(i.currency,'EGP'),1,now(),true
  ) RETURNING id INTO v_je;

  INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
  VALUES (v_je,v_ar,i.final_amount,0,'ذمم العميل - '||COALESCE(i.customer_name,''),1);
  IF v_net > 0 THEN
    INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
    VALUES (v_je,v_revenue,0,v_net,'صافي إيراد فاتورة '||i.invoice_number,2);
  END IF;
  IF COALESCE(i.vat_amount,0)>0 THEN
    INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
    VALUES (v_je,v_tax,0,i.vat_amount,'ضريبة القيمة المضافة',3);
  END IF;
  RETURN v_je;
END;
$$;

CREATE OR REPLACE FUNCTION public.post_customer_payment(_payment_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.customer_payments%ROWTYPE;
  v_je uuid;
  v_cash uuid;
  v_ar uuid;
  v_advance uuid;
  v_treasury_kind text;
  v_treasury_currency text;
  v_allocated numeric;
  v_unallocated numeric;
BEGIN
  SELECT * INTO p FROM public.customer_payments WHERE id=_payment_id;
  IF NOT FOUND THEN RETURN NULL; END IF;

  SELECT id INTO v_je FROM public.journal_entries
  WHERE organization_id=p.organization_id AND source_type='customer_payment' AND source_id=p.id;

  IF p.is_demo OR p.status<>'completed' THEN
    IF v_je IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
    ) THEN DELETE FROM public.journal_entries WHERE id=v_je; END IF;
    RETURN NULL;
  END IF;
  IF v_je IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
  ) THEN RETURN v_je; END IF;

  IF p.treasury_account_id IS NOT NULL THEN
    SELECT treasury_kind,COALESCE(currency,'EGP')
      INTO v_treasury_kind,v_treasury_currency
    FROM public.bank_accounts
    WHERE id=p.treasury_account_id AND organization_id=p.organization_id AND is_active;
    IF NOT FOUND OR v_treasury_currency<>p.currency THEN
      RAISE EXCEPTION 'Customer payment treasury is missing, inactive, or uses another currency';
    END IF;
  ELSIF p.payment_method<>'cash' THEN
    RAISE EXCEPTION 'A treasury account is required for non-cash customer payments';
  END IF;
  v_cash := public._resolve_account(
    p.organization_id,
    CASE WHEN COALESCE(v_treasury_kind,p.payment_method)='cash' THEN '1000' ELSE '1010' END
  );
  v_ar := public._resolve_account(p.organization_id,'1100');
  v_advance := public._resolve_account(p.organization_id,'2050');
  SELECT COALESCE(SUM(amount),0) INTO v_allocated
  FROM public.customer_payment_allocations WHERE payment_id=p.id;
  v_allocated := LEAST(v_allocated,p.amount);
  v_unallocated := p.amount-v_allocated;

  IF v_cash IS NULL OR (v_allocated>0 AND v_ar IS NULL)
     OR (v_unallocated>0 AND v_advance IS NULL) THEN
    RAISE EXCEPTION 'Missing cash/AR/customer-advance account for organization %', p.organization_id;
  END IF;

  DELETE FROM public.journal_entries WHERE id=v_je AND NOT is_locked;
  INSERT INTO public.journal_entries (
    organization_id,entry_number,entry_date,reference_type,reference_id,description,
    total_debit,total_credit,status,currency,source_type,source_id,booking_id,
    functional_currency,fx_rate,posted_at,auto_generated
  ) VALUES (
    p.organization_id,public._next_entry_number(p.organization_id),p.payment_date,
    'customer_payment',p.id,'دفعة عميل '||COALESCE(p.reference_number,p.id::text),
    p.amount,p.amount,'posted',p.currency,'customer_payment',p.id,p.booking_id,
    p.currency,p.exchange_rate,now(),true
  ) RETURNING id INTO v_je;

  INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
  VALUES (v_je,v_cash,p.amount,0,'تحصيل من العميل',1);
  IF v_allocated>0 THEN
    INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
    VALUES (v_je,v_ar,0,v_allocated,'تسوية ذمم عميل',2);
  END IF;
  IF v_unallocated>0 THEN
    INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
    VALUES (v_je,v_advance,0,v_unallocated,'دفعة مقدمة/رصيد دائن للعميل',3);
  END IF;
  RETURN v_je;
END;
$$;

-- Imported invoices often contain a paid total but predate the structured
-- customer_payments table. Post only the residual paid amount that is not
-- already represented by a payment allocation, so AR remains correct without
-- duplicating modern receipts.
CREATE OR REPLACE FUNCTION public.post_invoice_legacy_receipt(_invoice_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  i public.invoices%ROWTYPE;
  v_je uuid;
  v_bank uuid;
  v_ar uuid;
  v_allocated numeric;
  v_residual numeric;
BEGIN
  SELECT * INTO i FROM public.invoices WHERE id=_invoice_id;
  IF NOT FOUND OR i.organization_id IS NULL THEN RETURN NULL; END IF;
  SELECT id INTO v_je FROM public.journal_entries
  WHERE organization_id=i.organization_id
    AND source_type='legacy_invoice_receipt' AND source_id=i.id;

  SELECT COALESCE(SUM(a.amount),0) INTO v_allocated
  FROM public.customer_payment_allocations a
  JOIN public.customer_payments p ON p.id=a.payment_id AND p.status='completed'
  WHERE a.invoice_id=i.id;
  v_residual := GREATEST(COALESCE(i.total_paid_amount,0)-v_allocated,0);

  IF i.is_demo OR v_residual<=0 THEN
    IF v_je IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
    ) THEN DELETE FROM public.journal_entries WHERE id=v_je; END IF;
    RETURN NULL;
  END IF;
  IF v_je IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
  ) THEN RETURN v_je; END IF;

  v_bank:=COALESCE(public._resolve_account(i.organization_id,'1010'),
                   public._resolve_account(i.organization_id,'1000'));
  v_ar:=public._resolve_account(i.organization_id,'1100');
  IF v_bank IS NULL OR v_ar IS NULL THEN
    RAISE EXCEPTION 'Missing bank/AR account for organization %',i.organization_id;
  END IF;

  DELETE FROM public.journal_entries WHERE id=v_je AND NOT is_locked;
  INSERT INTO public.journal_entries(
    organization_id,entry_number,entry_date,reference_type,reference_id,description,
    total_debit,total_credit,status,currency,source_type,source_id,booking_id,
    functional_currency,fx_rate,posted_at,auto_generated
  ) VALUES (
    i.organization_id,public._next_entry_number(i.organization_id),
    COALESCE(i.issued_date,i.created_at::date,CURRENT_DATE),'legacy_invoice_receipt',i.id,
    'تحصيل تاريخي مثبت على الفاتورة '||i.invoice_number,v_residual,v_residual,'posted',
    COALESCE(i.currency,'EGP'),'legacy_invoice_receipt',i.id,i.booking_id,
    COALESCE(i.currency,'EGP'),1,now(),true
  ) RETURNING id INTO v_je;
  INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
  VALUES
    (v_je,v_bank,v_residual,0,'تحصيل تاريخي - وسيلة السداد غير مستوردة',1),
    (v_je,v_ar,0,v_residual,'تسوية ذمم فاتورة تاريخية',2);
  RETURN v_je;
END;
$$;

CREATE OR REPLACE FUNCTION public.post_supplier_payment(_payment_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.supplier_payments%ROWTYPE;
  v_je uuid;
  v_cash uuid;
  v_ap uuid;
  v_treasury_kind text;
  v_treasury_currency text;
BEGIN
  SELECT * INTO p FROM public.supplier_payments WHERE id=_payment_id;
  IF NOT FOUND OR p.organization_id IS NULL THEN RETURN NULL; END IF;

  SELECT id INTO v_je FROM public.journal_entries
  WHERE organization_id=p.organization_id AND source_type='supplier_payment' AND source_id=p.id;
  IF COALESCE(p.status,'pending') NOT IN ('paid','completed') THEN
    IF v_je IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
    ) THEN DELETE FROM public.journal_entries WHERE id=v_je; END IF;
    RETURN NULL;
  END IF;
  IF v_je IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
  ) THEN RETURN v_je; END IF;

  IF p.treasury_account_id IS NOT NULL THEN
    SELECT treasury_kind,COALESCE(currency,'EGP')
      INTO v_treasury_kind,v_treasury_currency
    FROM public.bank_accounts
    WHERE id=p.treasury_account_id AND organization_id=p.organization_id AND is_active;
    IF NOT FOUND OR v_treasury_currency<>COALESCE(p.currency,'EGP') THEN
      RAISE EXCEPTION 'Supplier payment treasury is missing, inactive, or uses another currency';
    END IF;
  ELSIF p.payment_method<>'cash' THEN
    RAISE EXCEPTION 'A treasury account is required for non-cash supplier payments';
  END IF;
  v_cash := public._resolve_account(
    p.organization_id,
    CASE WHEN COALESCE(v_treasury_kind,p.payment_method)='cash' THEN '1000' ELSE '1010' END
  );
  v_ap := public._resolve_account(p.organization_id,'2000');
  IF v_cash IS NULL OR v_ap IS NULL THEN
    RAISE EXCEPTION 'Missing cash/AP account for organization %', p.organization_id;
  END IF;

  DELETE FROM public.journal_entries WHERE id=v_je AND NOT is_locked;
  INSERT INTO public.journal_entries (
    organization_id,entry_number,entry_date,reference_type,reference_id,description,
    total_debit,total_credit,status,currency,source_type,source_id,booking_id,
    functional_currency,fx_rate,posted_at,auto_generated
  ) VALUES (
    p.organization_id,public._next_entry_number(p.organization_id),
    COALESCE(p.paid_date,p.payment_date,CURRENT_DATE),'supplier_payment',p.id,
    'سداد مورد '||COALESCE(p.reference_number,''),p.amount,p.amount,'posted',
    COALESCE(p.currency,'EGP'),'supplier_payment',p.id,p.booking_id,
    COALESCE(p.currency,'EGP'),COALESCE(p.exchange_rate,1),now(),true
  ) RETURNING id INTO v_je;
  INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
  VALUES
    (v_je,v_ap,p.amount,0,'تسوية ذمم المورد',1),
    (v_je,v_cash,0,p.amount,'صرف للمورد',2);
  RETURN v_je;
END;
$$;

CREATE OR REPLACE FUNCTION public.post_expense_transaction(_expense_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  e public.expense_transactions%ROWTYPE;
  v_je uuid;
  v_cash uuid;
  v_expense uuid;
  v_treasury_kind text;
  v_treasury_currency text;
BEGIN
  SELECT * INTO e FROM public.expense_transactions WHERE id=_expense_id;
  IF NOT FOUND OR e.organization_id IS NULL THEN RETURN NULL; END IF;

  SELECT id INTO v_je FROM public.journal_entries
  WHERE organization_id=e.organization_id AND source_type='expense' AND source_id=e.id;
  IF COALESCE(e.status,'pending') NOT IN ('approved','paid') THEN
    IF v_je IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
    ) THEN DELETE FROM public.journal_entries WHERE id=v_je; END IF;
    RETURN NULL;
  END IF;
  IF v_je IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.journal_entries WHERE id=v_je AND is_locked
  ) THEN RETURN v_je; END IF;

  IF e.bank_account_id IS NOT NULL THEN
    SELECT treasury_kind,COALESCE(currency,'EGP')
      INTO v_treasury_kind,v_treasury_currency
    FROM public.bank_accounts
    WHERE id=e.bank_account_id AND organization_id=e.organization_id AND is_active;
    IF NOT FOUND OR v_treasury_currency<>COALESCE(e.currency,'EGP') THEN
      RAISE EXCEPTION 'Expense treasury is missing, inactive, or uses another currency';
    END IF;
  ELSIF e.payment_method<>'cash' THEN
    RAISE EXCEPTION 'A treasury account is required for non-cash expenses';
  END IF;
  v_cash := public._resolve_account(
    e.organization_id,
    CASE WHEN COALESCE(v_treasury_kind,e.payment_method)='cash' THEN '1000' ELSE '1010' END
  );
  v_expense := public._resolve_account(e.organization_id,'6900');
  IF v_cash IS NULL OR v_expense IS NULL THEN
    RAISE EXCEPTION 'Missing cash/general-expense account for organization %', e.organization_id;
  END IF;

  DELETE FROM public.journal_entries WHERE id=v_je AND NOT is_locked;
  INSERT INTO public.journal_entries (
    organization_id,entry_number,entry_date,reference_type,reference_id,description,
    total_debit,total_credit,status,currency,source_type,source_id,booking_id,
    functional_currency,fx_rate,posted_at,auto_generated
  ) VALUES (
    e.organization_id,public._next_entry_number(e.organization_id),
    COALESCE(e.transaction_date,CURRENT_DATE),'expense',e.id,e.description,
    e.amount,e.amount,'posted',COALESCE(e.currency,'EGP'),'expense',e.id,e.booking_id,
    COALESCE(e.currency,'EGP'),1,now(),true
  ) RETURNING id INTO v_je;
  INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
  VALUES
    (v_je,v_expense,e.amount,0,e.description,1),
    (v_je,v_cash,0,e.amount,'سداد مصروف',2);
  RETURN v_je;
END;
$$;

-- Thin triggers intentionally do not swallow exceptions. A financial write and
-- its journal must either both succeed or both roll back.
CREATE OR REPLACE FUNCTION public._trg_post_booking_cost()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN PERFORM public.post_booking_cost(NEW.id); RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION public._trg_post_invoice()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN PERFORM public.post_invoice(NEW.id); RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION public._trg_post_customer_payment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN PERFORM public.post_customer_payment(NEW.id); RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION public._trg_post_invoice_legacy_receipt()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN PERFORM public.post_invoice_legacy_receipt(NEW.id); RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION public._trg_post_supplier_payment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN PERFORM public.post_supplier_payment(NEW.id); RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION public._trg_post_expense()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN PERFORM public.post_expense_transaction(NEW.id); RETURN NEW; END $$;

CREATE TRIGGER trg_post_booking_cost
AFTER INSERT OR UPDATE OF status,cost_price,currency,start_date,booking_type,is_demo
ON public.bookings FOR EACH ROW EXECUTE FUNCTION public._trg_post_booking_cost();

CREATE TRIGGER trg_post_invoice
AFTER INSERT OR UPDATE OF subtotal,discount_amount,vat_rate,vat_amount,final_amount,
  status,issued_date,currency,booking_type,is_demo
ON public.invoices FOR EACH ROW EXECUTE FUNCTION public._trg_post_invoice();

CREATE TRIGGER trg_post_invoice_legacy_receipt
AFTER INSERT OR UPDATE OF total_paid_amount,status,issued_date,currency,is_demo
ON public.invoices FOR EACH ROW EXECUTE FUNCTION public._trg_post_invoice_legacy_receipt();

CREATE TRIGGER trg_customer_payment_to_journal
AFTER INSERT OR UPDATE OF status,amount,currency,payment_date,payment_method,treasury_account_id
ON public.customer_payments FOR EACH ROW EXECUTE FUNCTION public._trg_post_customer_payment();

CREATE TRIGGER trg_post_supplier_payment
AFTER INSERT OR UPDATE OF status,amount,currency,payment_date,paid_date,payment_method,treasury_account_id
ON public.supplier_payments FOR EACH ROW EXECUTE FUNCTION public._trg_post_supplier_payment();

CREATE TRIGGER trg_post_expense
AFTER INSERT OR UPDATE OF status,amount,currency,transaction_date,payment_method,bank_account_id
ON public.expense_transactions FOR EACH ROW EXECUTE FUNCTION public._trg_post_expense();

-- ---------------------------------------------------------------------------
-- 6) Transaction-safe payment RPCs.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.record_customer_payment(
  _invoice_id uuid, _amount numeric, _currency text DEFAULT 'EGP',
  _exchange_rate numeric DEFAULT 1, _method text DEFAULT 'cash',
  _treasury_account_id uuid DEFAULT NULL, _payment_date date DEFAULT CURRENT_DATE,
  _reference text DEFAULT NULL, _notes text DEFAULT NULL, _client_ref text DEFAULT NULL,
  _booking_id uuid DEFAULT NULL, _customer_id uuid DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
  v_org uuid;
  v_payment_id uuid;
  v_booking uuid := _booking_id;
  v_customer uuid := _customer_id;
  v_final numeric := 0;
  v_paid numeric := 0;
  v_allocate numeric := 0;
  v_base numeric;
  v_treasury_currency text;
BEGIN
  IF _amount IS NULL OR _amount<=0 OR COALESCE(_exchange_rate,0)<=0 THEN
    RAISE EXCEPTION 'Payment amount and exchange rate must be positive';
  END IF;

  IF _invoice_id IS NOT NULL THEN
    SELECT organization_id,booking_id,customer_id,final_amount,total_paid_amount
      INTO v_org,v_booking,v_customer,v_final,v_paid
    FROM public.invoices WHERE id=_invoice_id FOR UPDATE;
    IF v_org IS NULL THEN RAISE EXCEPTION 'Invoice not found'; END IF;
    IF COALESCE((SELECT currency FROM public.invoices WHERE id=_invoice_id),'EGP')<>_currency THEN
      RAISE EXCEPTION 'Payment currency must match invoice currency';
    END IF;
    v_allocate := LEAST(_amount,GREATEST(COALESCE(v_final,0)-COALESCE(v_paid,0),0));
  ELSIF v_booking IS NOT NULL THEN
    SELECT organization_id,customer_id INTO v_org,v_customer
    FROM public.bookings WHERE id=v_booking;
  END IF;

  IF v_org IS NULL THEN RAISE EXCEPTION 'Organization could not be resolved'; END IF;
  IF NOT public.can_org_write(v_org) THEN RAISE EXCEPTION 'Not authorized'; END IF;

  IF _treasury_account_id IS NOT NULL THEN
    SELECT currency INTO v_treasury_currency FROM public.bank_accounts
    WHERE id=_treasury_account_id AND organization_id=v_org AND is_active;
    IF v_treasury_currency IS NULL THEN RAISE EXCEPTION 'Treasury account not found'; END IF;
    IF v_treasury_currency<>_currency THEN RAISE EXCEPTION 'Treasury currency must match payment currency'; END IF;
  ELSIF COALESCE(_method,'cash')<>'cash' THEN
    RAISE EXCEPTION 'A treasury account is required for non-cash payments';
  END IF;

  IF _client_ref IS NOT NULL THEN
    SELECT id INTO v_payment_id FROM public.customer_payments
    WHERE organization_id=v_org AND client_ref=_client_ref;
    IF v_payment_id IS NOT NULL THEN RETURN v_payment_id; END IF;
  END IF;

  v_base := round(_amount*_exchange_rate,2);
  INSERT INTO public.customer_payments (
    organization_id,booking_id,customer_id,invoice_id,treasury_account_id,
    amount,currency,exchange_rate,amount_base,payment_method,reference_number,
    payment_date,notes,status,client_ref,created_by
  ) VALUES (
    v_org,v_booking,v_customer,_invoice_id,_treasury_account_id,
    _amount,_currency,_exchange_rate,v_base,_method,_reference,
    _payment_date,_notes,'pending',_client_ref,auth.uid()
  ) RETURNING id INTO v_payment_id;

  IF _invoice_id IS NOT NULL AND v_allocate>0 THEN
    INSERT INTO public.customer_payment_allocations(
      organization_id,payment_id,invoice_id,amount,amount_base
    ) VALUES (v_org,v_payment_id,_invoice_id,v_allocate,round(v_allocate*_exchange_rate,2));
    UPDATE public.invoices
    SET total_paid_amount=LEAST(final_amount,COALESCE(total_paid_amount,0)+v_allocate)
    WHERE id=_invoice_id;
  END IF;

  IF _treasury_account_id IS NOT NULL THEN
    UPDATE public.bank_accounts
    SET current_balance=COALESCE(current_balance,0)+_amount,updated_at=now()
    WHERE id=_treasury_account_id;
    INSERT INTO public.bank_account_transactions(
      bank_account_id,transaction_type,amount,description,transaction_date,
      reference_number,related_invoice_id,organization_id,created_by
    ) VALUES (
      _treasury_account_id,'deposit',_amount,COALESCE(_notes,'Customer payment'),
      _payment_date,_reference,_invoice_id,v_org,auth.uid()
    );
  END IF;

  INSERT INTO public.finance_transactions(
    organization_id,booking_id,reference_type,reference_id,account_code,
    party_type,party_id,direction,amount,currency,exchange_rate,amount_base,memo,created_by
  ) VALUES
    (v_org,v_booking,'customer_payment',v_payment_id,
      CASE WHEN _method='cash' AND _treasury_account_id IS NULL THEN '1000' ELSE '1010' END,
      'treasury',_treasury_account_id,'debit',_amount,_currency,_exchange_rate,v_base,'Customer payment received',auth.uid());
  IF v_allocate>0 THEN
    INSERT INTO public.finance_transactions(
      organization_id,booking_id,reference_type,reference_id,account_code,
      party_type,party_id,direction,amount,currency,exchange_rate,amount_base,memo,created_by
    ) VALUES (v_org,v_booking,'customer_payment',v_payment_id,'1100','customer',v_customer,
      'credit',v_allocate,_currency,_exchange_rate,round(v_allocate*_exchange_rate,2),'Accounts receivable reduction',auth.uid());
  END IF;
  IF _amount-v_allocate>0 THEN
    INSERT INTO public.finance_transactions(
      organization_id,booking_id,reference_type,reference_id,account_code,
      party_type,party_id,direction,amount,currency,exchange_rate,amount_base,memo,created_by
    ) VALUES (v_org,v_booking,'customer_payment',v_payment_id,'2050','customer',v_customer,
      'credit',_amount-v_allocate,_currency,_exchange_rate,round((_amount-v_allocate)*_exchange_rate,2),'Customer advance',auth.uid());
  END IF;

  UPDATE public.customer_payments SET status='completed' WHERE id=v_payment_id;
  RETURN v_payment_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_supplier_payment(
  _po_id uuid, _amount numeric, _currency text DEFAULT 'EGP', _exchange_rate numeric DEFAULT 1,
  _method text DEFAULT 'bank_transfer', _treasury_account_id uuid DEFAULT NULL,
  _payment_date date DEFAULT CURRENT_DATE, _reference text DEFAULT NULL, _notes text DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
  v_po public.supplier_payment_orders%ROWTYPE;
  v_payment_id uuid;
  v_allocated numeric;
  v_remaining numeric;
  v_base numeric;
  v_treasury_currency text;
BEGIN
  IF _amount IS NULL OR _amount<=0 OR COALESCE(_exchange_rate,0)<=0 THEN
    RAISE EXCEPTION 'Payment amount and exchange rate must be positive';
  END IF;
  SELECT * INTO v_po FROM public.supplier_payment_orders WHERE id=_po_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Payment order not found'; END IF;
  IF NOT public.can_org_write(v_po.organization_id) THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF v_po.approval_status<>'approved' THEN RAISE EXCEPTION 'Payment order must be approved'; END IF;
  IF v_po.currency<>_currency THEN RAISE EXCEPTION 'Payment currency must match payment order currency'; END IF;

  SELECT COALESCE(SUM(amount),0) INTO v_allocated
  FROM public.supplier_payment_allocations WHERE payment_order_id=_po_id;
  v_remaining := GREATEST(v_po.amount-v_allocated,0);
  IF _amount>v_remaining THEN
    RAISE EXCEPTION 'Payment exceeds the remaining payment-order balance (%)',v_remaining;
  END IF;

  IF _treasury_account_id IS NOT NULL THEN
    SELECT currency INTO v_treasury_currency FROM public.bank_accounts
    WHERE id=_treasury_account_id AND organization_id=v_po.organization_id AND is_active;
    IF v_treasury_currency IS NULL THEN RAISE EXCEPTION 'Treasury account not found'; END IF;
    IF v_treasury_currency<>_currency THEN RAISE EXCEPTION 'Treasury currency must match payment currency'; END IF;
  ELSIF COALESCE(_method,'bank_transfer')<>'cash' THEN
    RAISE EXCEPTION 'A treasury account is required for non-cash supplier payments';
  END IF;

  v_base:=round(_amount*_exchange_rate,2);
  INSERT INTO public.supplier_payments(
    supplier_id,amount,currency,payment_date,payment_method,reference_number,
    booking_id,notes,status,created_by,paid_date,amount_in_egp,exchange_rate,
    organization_id,treasury_account_id
  ) VALUES (
    v_po.supplier_id,_amount,_currency,_payment_date,_method,_reference,
    v_po.booking_id,_notes,'pending',auth.uid(),_payment_date,v_base,_exchange_rate,
    v_po.organization_id,_treasury_account_id
  ) RETURNING id INTO v_payment_id;

  INSERT INTO public.supplier_payment_allocations(
    organization_id,supplier_payment_id,payment_order_id,amount,amount_base
  ) VALUES (v_po.organization_id,v_payment_id,_po_id,_amount,v_base);

  UPDATE public.supplier_payment_orders
  SET status=CASE WHEN _amount>=v_remaining THEN 'paid' ELSE 'partially_paid' END,
      updated_at=now()
  WHERE id=_po_id;

  IF _treasury_account_id IS NOT NULL THEN
    UPDATE public.bank_accounts
    SET current_balance=COALESCE(current_balance,0)-_amount,updated_at=now()
    WHERE id=_treasury_account_id;
    INSERT INTO public.bank_account_transactions(
      bank_account_id,transaction_type,amount,description,transaction_date,
      reference_number,related_payment_order_id,organization_id,created_by
    ) VALUES (
      _treasury_account_id,'withdrawal',_amount,COALESCE(_notes,'Supplier payment'),
      _payment_date,_reference,_po_id,v_po.organization_id,auth.uid()
    );
  END IF;

  INSERT INTO public.finance_transactions(
    organization_id,booking_id,reference_type,reference_id,account_code,
    party_type,party_id,direction,amount,currency,exchange_rate,amount_base,memo,created_by
  ) VALUES
    (v_po.organization_id,v_po.booking_id,'supplier_payment',v_payment_id,'2000','supplier',v_po.supplier_id,
      'debit',_amount,_currency,_exchange_rate,v_base,'Accounts payable reduction',auth.uid()),
    (v_po.organization_id,v_po.booking_id,'supplier_payment',v_payment_id,
      CASE WHEN _method='cash' AND _treasury_account_id IS NULL THEN '1000' ELSE '1010' END,
      'treasury',_treasury_account_id,'credit',_amount,_currency,_exchange_rate,v_base,'Supplier cash disbursement',auth.uid());

  UPDATE public.supplier_payments SET status='paid' WHERE id=v_payment_id;
  RETURN v_payment_id;
END;
$$;

-- ---------------------------------------------------------------------------
-- 7) Rebuild only deterministic, unlocked auto-postings from their source rows.
-- ---------------------------------------------------------------------------
INSERT INTO public.financial_repair_audit(
  migration_key,organization_id,entity_type,entity_id,before_data,reason
)
SELECT '20260822_financial_launch',je.organization_id,'journal_entry',je.id,
       to_jsonb(je)||jsonb_build_object(
         'lines',COALESCE((SELECT jsonb_agg(to_jsonb(l) ORDER BY l.line_order,l.id)
                           FROM public.journal_entry_lines l WHERE l.journal_entry_id=je.id),'[]'::jsonb)
       ),
       'Remove overlapping legacy auto-posting and rebuild from canonical source'
FROM public.journal_entries je
WHERE NOT je.is_locked
  AND (
    je.reference_type IN ('booking','booking_cost','hotel_cost','invoice','invoice_payment')
    OR je.source_type IN ('booking','booking_cost','invoice','legacy_invoice_receipt','customer_payment','supplier_payment','expense')
  );

DELETE FROM public.journal_entries je
WHERE NOT je.is_locked
  AND (
    je.reference_type IN ('booking','booking_cost','hotel_cost','invoice','invoice_payment')
    OR je.source_type IN ('booking','booking_cost','invoice','legacy_invoice_receipt','customer_payment','supplier_payment','expense')
  );

DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT id FROM public.bookings LOOP
    PERFORM public.post_booking_cost(r.id);
  END LOOP;
  FOR r IN SELECT id FROM public.invoices LOOP
    PERFORM public.post_invoice(r.id);
    PERFORM public.post_invoice_legacy_receipt(r.id);
  END LOOP;
  FOR r IN SELECT id FROM public.customer_payments LOOP
    PERFORM public.post_customer_payment(r.id);
  END LOOP;
  FOR r IN SELECT id FROM public.supplier_payments LOOP
    PERFORM public.post_supplier_payment(r.id);
  END LOOP;
  FOR r IN SELECT id FROM public.expense_transactions LOOP
    PERFORM public.post_expense_transaction(r.id);
  END LOOP;
END $$;

-- Reconcile the rebuilt cash ledger to the treasury balances explicitly stored
-- by each organization. This is a visible launch opening-balance entry, not a
-- silent rewrite, and it supplies the historical opening figure that imports
-- did not contain.
DO $$
DECLARE
  r record;
  v_entry uuid;
  v_cash uuid;
  v_equity uuid;
BEGIN
  FOR r IN
    WITH treasury AS (
      SELECT organization_id,COALESCE(currency,'EGP') AS currency,
             CASE WHEN treasury_kind='cash' THEN '1000' ELSE '1010' END AS account_code,
             SUM(COALESCE(current_balance,0)) AS target_balance
      FROM public.bank_accounts
      WHERE COALESCE(is_active,true)
      GROUP BY organization_id,COALESCE(currency,'EGP'),
               CASE WHEN treasury_kind='cash' THEN '1000' ELSE '1010' END
    ), ledger AS (
      SELECT je.organization_id,je.currency,a.account_code,
             SUM(l.debit-l.credit) AS ledger_balance
      FROM public.journal_entries je
      JOIN public.journal_entry_lines l ON l.journal_entry_id=je.id
      JOIN public.chart_of_accounts a ON a.id=l.account_id
      WHERE je.status='posted' AND a.account_code IN ('1000','1010')
        AND je.source_type IS DISTINCT FROM 'launch_opening_balance'
        AND je.entry_date<=CURRENT_DATE
      GROUP BY je.organization_id,je.currency,a.account_code
    )
    SELECT COALESCE(t.organization_id,l.organization_id) AS organization_id,
           COALESCE(t.currency,l.currency) AS currency,
           COALESCE(t.account_code,l.account_code) AS account_code,
           COALESCE(t.target_balance,0) AS target_balance,
           COALESCE(l.ledger_balance,0) AS ledger_balance,
           COALESCE(t.target_balance,0)-COALESCE(l.ledger_balance,0) AS difference
    FROM treasury t
    FULL JOIN ledger l USING(organization_id,currency,account_code)
    WHERE abs(COALESCE(t.target_balance,0)-COALESCE(l.ledger_balance,0))>0.01
  LOOP
    v_cash:=public._resolve_account(r.organization_id,r.account_code);
    v_equity:=public._resolve_account(r.organization_id,'3000');
    IF v_cash IS NULL OR v_equity IS NULL THEN
      RAISE EXCEPTION 'Missing cash/equity account for launch balance in organization %',r.organization_id;
    END IF;
    INSERT INTO public.journal_entries(
      organization_id,entry_number,entry_date,reference_type,description,total_debit,total_credit,
      status,currency,source_type,source_id,functional_currency,fx_rate,posted_at,auto_generated
    ) VALUES (
      r.organization_id,public._next_entry_number(r.organization_id),
      COALESCE((SELECT MIN(entry_date)-1 FROM public.journal_entries
                WHERE organization_id=r.organization_id AND currency=r.currency),CURRENT_DATE),
      'launch_opening_balance','رصيد افتتاحي وتسوية ترحيل عند الإطلاق',
      abs(r.difference),abs(r.difference),'posted',r.currency,
      'launch_opening_balance',gen_random_uuid(),r.currency,1,now(),true
    ) RETURNING id INTO v_entry;
    IF r.difference>0 THEN
      INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
      VALUES
        (v_entry,v_cash,r.difference,0,'تسوية رصيد الخزينة إلى الرصيد المثبت',1),
        (v_entry,v_equity,0,r.difference,'رصيد افتتاحي مقابل',2);
    ELSE
      INSERT INTO public.journal_entry_lines(journal_entry_id,account_id,debit,credit,description,line_order)
      VALUES
        (v_entry,v_equity,abs(r.difference),0,'رصيد افتتاحي مقابل',1),
        (v_entry,v_cash,0,abs(r.difference),'تسوية رصيد الخزينة إلى الرصيد المثبت',2);
    END IF;
    INSERT INTO public.financial_repair_audit(
      migration_key,organization_id,entity_type,entity_id,after_data,reason
    ) VALUES (
      '20260822_financial_launch',r.organization_id,'journal_entry',v_entry,
      jsonb_build_object('currency',r.currency,'account_code',r.account_code,
                         'target_balance',r.target_balance,
                         'ledger_before',r.ledger_balance,'difference',r.difference),
      'Explicit launch opening balance reconciles imported ledger to treasury snapshot'
    );
  END LOOP;
END $$;

-- Fail the migration if any rebuilt header does not equal its lines.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.journal_entries je
    LEFT JOIN public.journal_entry_lines l ON l.journal_entry_id=je.id
    GROUP BY je.id,je.total_debit,je.total_credit
    HAVING abs(je.total_debit-COALESCE(SUM(l.debit),0))>0.01
        OR abs(je.total_credit-COALESCE(SUM(l.credit),0))>0.01
        OR abs(COALESCE(SUM(l.debit),0)-COALESCE(SUM(l.credit),0))>0.01
  ) THEN
    RAISE EXCEPTION 'Journal rebuild validation failed';
  END IF;
END $$;

REVOKE ALL ON FUNCTION public.post_booking_cost(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.post_invoice(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.post_customer_payment(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.post_invoice_legacy_receipt(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.post_supplier_payment(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.post_expense_transaction(uuid) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public._next_entry_number(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public._next_entry_number(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.post_booking_cost(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.post_invoice(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.post_customer_payment(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.post_invoice_legacy_receipt(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.post_supplier_payment(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.post_expense_transaction(uuid) TO service_role;

REVOKE ALL ON FUNCTION public.record_customer_payment(uuid,numeric,text,numeric,text,uuid,date,text,text,text,uuid,uuid) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.record_supplier_payment(uuid,numeric,text,numeric,text,uuid,date,text,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.record_customer_payment(uuid,numeric,text,numeric,text,uuid,date,text,text,text,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_supplier_payment(uuid,numeric,text,numeric,text,uuid,date,text,text) TO authenticated;

COMMIT;
