// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sazfojsdhjxcjungqory.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhemZvanNkaGp4Y2p1bmdxb3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTg5ODcsImV4cCI6MjA2NTQ5NDk4N30.zRS4ZJ7e-tkhmU4BMVRR7tzGkjTScwAErWcoALIoRs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);